// <auto-generated>
// 本文件由脚本自动生成，请勿手动修改。
// 分类体系基于游戏交互提示/组件/显示名与游戏机制设计（多标签），见 scripts/gen_category_multi.py。
// </auto-generated>
using System.Collections.Generic;

namespace ItemSpawnerEnhancement
{
    /// <summary>二级分类（Flags，一物可属多类）。</summary>
    [System.Flags]
    public enum ItemCategory : int
    {
        None = 0,
        Tools = 1,
        Food = 2,
        Mystical = 4,
        Equipment = 8,
        Consumables = 16,
        Props = 32,
    }

    /// <summary>一级分类（顶部横向按钮，全部 + 六类）。</summary>
    public enum MajorCategory : int
    {
        All = 0,
        Tools = 1,
        Food = 2,
        Mystical = 3,
        Equipment = 4,
        Consumables = 5,
        Props = 6,
    }

    public static partial class ItemCatalog
    {
        /// <summary>物品 prefab 名 -> 全部标签（Flags）。主分类由 ItemCatalog.PrimaryOfTags 运行时推导。</summary>
        public static readonly Dictionary<string, ItemCategory> ItemTagMap = new Dictionary<string, ItemCategory>(System.StringComparer.OrdinalIgnoreCase)
        {
            // 分类依据：游戏资源真值提取（item_truth.json）——itemTags / totalUses / 子树全部组件。
            // 消耗品 = totalUses>0（有使用次数）或 Action_Consume（一次性用完消失），食物除外。
            { "Airplane Food", ItemCategory.Food },
            { "AK", ItemCategory.Props },
            { "AloeVera", ItemCategory.Consumables },
            { "Amulet_Clone", ItemCategory.Mystical },
            { "Amulet_Healing", ItemCategory.Mystical },
            { "Amulet_InfiniteStamina", ItemCategory.Mystical },
            { "Amulet_SuperJump", ItemCategory.Mystical },
            { "AncientIdol", ItemCategory.Mystical },
            { "Anti-Rope Spool", ItemCategory.Consumables | ItemCategory.Mystical | ItemCategory.Tools },  // 绳索燃料耗尽后 Consume
            { "Antidote", ItemCategory.Consumables },
            { "AntiZooka", ItemCategory.Consumables | ItemCategory.Mystical | ItemCategory.Tools },  // 3 次
            { "Apple Berry Green", ItemCategory.Food },
            { "Apple Berry Red", ItemCategory.Food },
            { "Apple Berry Weird", ItemCategory.Food },
            { "Apple Berry Yellow", ItemCategory.Food },
            { "Backpack", ItemCategory.Equipment },
            { "Balloon", ItemCategory.Consumables },
            { "BalloonBunch", ItemCategory.Consumables },
            { "Bandages", ItemCategory.Consumables },
            { "Basketball", ItemCategory.Props },
            { "Beehive", ItemCategory.Props },
            { "Berrynana Blue", ItemCategory.Food },
            { "Berrynana Brown", ItemCategory.Food },
            { "Berrynana Peel Blue Variant", ItemCategory.Props },
            { "Berrynana Peel Brown Variant", ItemCategory.Props },
            { "Berrynana Peel Pink Variant", ItemCategory.Props },
            { "Berrynana Peel Yellow", ItemCategory.Props },
            { "Berrynana Pink", ItemCategory.Food },
            { "Berrynana Yellow", ItemCategory.Food },
            { "BingBong", ItemCategory.Equipment | ItemCategory.Mystical },
            { "Binoculars", ItemCategory.Equipment },
            { "BookOfBones", ItemCategory.Consumables | ItemCategory.Mystical },  // 1 次
            { "BounceShroom", ItemCategory.Tools },
            { "Bugfix", ItemCategory.Food },
            { "Bugle", ItemCategory.Equipment },
            { "Bugle_Magic", ItemCategory.Equipment | ItemCategory.Mystical },
            { "Bugle_Scoutmaster Variant", ItemCategory.Consumables | ItemCategory.Mystical },  // 1 次
            { "CactusBall", ItemCategory.Props },
            { "Candle", ItemCategory.Consumables | ItemCategory.Tools },        // 光源：燃料耗尽
            { "ChainShooter", ItemCategory.Consumables | ItemCategory.Tools },  // 1 次
            { "Cheat Compass", ItemCategory.Consumables | ItemCategory.Mystical },     // 1 次
            { "Cheat Compass 1", ItemCategory.Consumables | ItemCategory.Mystical },   // 1 次
            { "ClimbingChalk", ItemCategory.Consumables | ItemCategory.Mystical },     // 1 次
            { "ClimbingSpike", ItemCategory.Tools },
            { "CloudFungus", ItemCategory.Tools },
            { "Clusterberry Black", ItemCategory.Food },
            { "Clusterberry Red", ItemCategory.Food },
            { "Clusterberry Yellow", ItemCategory.Food },
            { "Compass", ItemCategory.Equipment },
            { "Cure-All", ItemCategory.Consumables | ItemCategory.Mystical },   // 3 次
            { "Cure-Some", ItemCategory.Consumables | ItemCategory.Mystical },
            { "Cursed Skull", ItemCategory.Mystical },
            { "Darkberry", ItemCategory.Food | ItemCategory.Mystical },
            { "Dynamite", ItemCategory.Consumables },                           // 1 次
            { "EarlyWorm", ItemCategory.Food },
            { "Egg", ItemCategory.Food },
            { "EggRaven", ItemCategory.Food },
            { "EggTurkey", ItemCategory.Food },
            { "Energy Drink", ItemCategory.Food },
            { "Energy Elixir", ItemCategory.Consumables | ItemCategory.Mystical },
            { "Fannypack", ItemCategory.Equipment },
            { "FireWood", ItemCategory.Props },
            { "FirstAidKit", ItemCategory.Consumables },
            { "Flag_Plantable_Checkpoint", ItemCategory.Consumables | ItemCategory.Tools },
            { "Flare", ItemCategory.Consumables },                              // 1 次
            { "FortifiedMilk", ItemCategory.Food },
            { "Frisbee", ItemCategory.Props },
            { "Frog", ItemCategory.Food },
            { "FrogLegs", ItemCategory.Food },
            { "Glider", ItemCategory.Equipment },
            { "Glizzy", ItemCategory.Food },
            { "Glizzy_CattailVariant", ItemCategory.Food },
            { "Granola Bar", ItemCategory.Food },
            { "Guidebook", ItemCategory.Equipment },
            { "HealingDart Variant", ItemCategory.Consumables | ItemCategory.Tools },  // 1 次
            { "HealingPuffShroom", ItemCategory.Consumables | ItemCategory.Tools },  // 砸地碎裂放出绿烟清除负面状态（ShelfShroom 族，投出即自毁）
            { "Heat Pack", ItemCategory.Consumables },
            { "Item_Coconut", ItemCategory.Food | ItemCategory.Props },  // 整颗需砸开（Breakable+Bonkable），本身零交互投掷物
            { "Item_Coconut_half", ItemCategory.Food },
            { "Item_Honeycomb", ItemCategory.Food },
            { "Jetpack", ItemCategory.Equipment },
            { "Kingberry Green", ItemCategory.Food },
            { "Kingberry Purple", ItemCategory.Food },
            { "Kingberry Yellow", ItemCategory.Food },
            { "Lantern", ItemCategory.Consumables | ItemCategory.Tools },       // 光源：燃料耗尽
            { "Lantern_Faerie", ItemCategory.Consumables | ItemCategory.Mystical | ItemCategory.Tools },
            { "Lollipop", ItemCategory.Food },
            { "Lollipop_Evil", ItemCategory.Food | ItemCategory.Mystical },
            { "MagicBean", ItemCategory.Consumables | ItemCategory.Mystical | ItemCategory.Tools },  // 种下生成藤蔓后本体销毁
            { "Mandrake", ItemCategory.Food },
            { "Marshmallow", ItemCategory.Food },
            { "Matchbook", ItemCategory.Equipment },   // 实为查看叠加层（同望远镜），非光源
            { "MedicinalRoot", ItemCategory.Food },
            { "Megaphone", ItemCategory.Equipment },
            { "Mushroom Chubby", ItemCategory.Food },
            { "Mushroom Cluster", ItemCategory.Food },
            { "Mushroom Cluster Poison", ItemCategory.Food },
            { "Mushroom Glow", ItemCategory.Food },
            { "Mushroom Lace", ItemCategory.Food },
            { "Mushroom Lace Poison", ItemCategory.Food },
            { "Mushroom Normie", ItemCategory.Food },
            { "Mushroom Normie Poison", ItemCategory.Food },
            { "Napberry", ItemCategory.Food },
            { "NestEgg", ItemCategory.Food },
            { "NestEgg_Raven", ItemCategory.Food },
            { "Painkillers", ItemCategory.Consumables },
            { "PandorasBox", ItemCategory.Consumables | ItemCategory.Mystical },  // 3 次
            { "Parachute", ItemCategory.Consumables | ItemCategory.Equipment },  // 坠落自动触发，用后 Consume
            { "Parasol", ItemCategory.Equipment },
            { "Parasol_Roots Variant", ItemCategory.Equipment },
            { "Passport", ItemCategory.Equipment },
            { "Pepper Berry", ItemCategory.Food },
            { "Pirate Compass", ItemCategory.Equipment },
            { "PortableStovetopItem", ItemCategory.Consumables | ItemCategory.Tools },
            { "Prickleberry_Gold", ItemCategory.Food },
            { "Prickleberry_Red", ItemCategory.Food },
            { "RescueHook", ItemCategory.Consumables | ItemCategory.Tools },    // 3 次
            { "RescueHook_Infinite", ItemCategory.Tools },                      // 无限次
            { "RitualDagger", ItemCategory.Mystical },
            { "Rocketpack", ItemCategory.Consumables | ItemCategory.Equipment },  // 占背包位，燃尽爆炸自毁
            { "RopeShooter", ItemCategory.Consumables | ItemCategory.Tools },   // 1 次
            { "RopeShooterAnti", ItemCategory.Consumables | ItemCategory.Mystical | ItemCategory.Tools },
            { "RopeSpool", ItemCategory.Consumables | ItemCategory.Tools },  // 绳索燃料耗尽后 Consume
            { "Scorpion", ItemCategory.Food },
            { "ScoutCannonItem", ItemCategory.Consumables | ItemCategory.Tools },
            { "ScoutCookies", ItemCategory.Consumables | ItemCategory.Food },        // 4 次用量（Action_ReduceUses），唯一带次数计数的食物
            { "ScoutCookies_Vanilla", ItemCategory.Consumables | ItemCategory.Food }, // 同上
            { "ScoutEffigy", ItemCategory.Consumables | ItemCategory.Mystical },
            { "ScoutmasterSoul", ItemCategory.Mystical },
            { "ScoutsHonor", ItemCategory.Mystical },
            { "ShelfShroom", ItemCategory.Tools },
            { "Shell Big", ItemCategory.Props },
            { "Shroomberry_Blue", ItemCategory.Food },
            { "Shroomberry_Green", ItemCategory.Food },
            { "Shroomberry_Purple", ItemCategory.Food },
            { "Shroomberry_Red", ItemCategory.Food },
            { "Shroomberry_Yellow", ItemCategory.Food },
            { "Skyberry", ItemCategory.Food },
            { "Snowball", ItemCategory.Props },
            { "Sports Drink", ItemCategory.Food },
            { "Stone", ItemCategory.Props },
            { "Strange Gem", ItemCategory.Mystical },
            { "Sunscreen", ItemCategory.Consumables },                          // 3 次
            { "Torch", ItemCategory.Consumables | ItemCategory.Tools },         // 光源：燃料耗尽
            { "TrailMix", ItemCategory.Food },
            { "Wand of Wind", ItemCategory.Consumables | ItemCategory.Mystical },  // 3 次
            { "Warp Compass", ItemCategory.Consumables | ItemCategory.Mystical },  // 3 次
            { "WarpFungus", ItemCategory.Mystical | ItemCategory.Tools },
            { "Warpsketball", ItemCategory.Props },
            { "Winterberry Orange", ItemCategory.Food },
            { "Winterberry Yellow", ItemCategory.Food },
            { "Wonderberry", ItemCategory.Food | ItemCategory.Mystical },
            { "Yuzu Berry", ItemCategory.Food },
        };

        /// <summary>
        /// 补充本地化 key 映射：prefab 名 -> 本地化 key（UIData.itemName 与游戏表不对应时使用）。
        /// 说明：当前游戏版本下这些 key 与 "NAME_" + UIData.itemName 的默认解析结果一致，
        /// 保留作为版本兼容兜底（若未来 UIData.itemName 改动，此表可锁定正确 key）。
        /// </summary>
        public static readonly Dictionary<string, string> ExtraNameKeys = new Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)
        {
            { "Bugfix", "NAME_TICK" },
            { "EggRaven", "NAME_EGG" },
            { "EggTurkey", "NAME_BIRD" },
            { "NestEgg", "NAME_BIG EGG" },
            { "NestEgg_Raven", "NAME_SMALL EGG" },
            { "Parachute", "NAME_AUTOPARACHUTE" },
        };

        /// <summary>补充自定义名称：prefab 名 -> [中文名, 英文显示名]（游戏本地化表缺失的物品）。</summary>
        public static readonly Dictionary<string, string[]> ExtraCustomNames = new Dictionary<string, string[]>(System.StringComparer.OrdinalIgnoreCase)
        {
            { "AK", new string[] { "AK", "AK" } },
            { "Apple Berry Weird", new string[] { "诡异脆莓", "Weird Crispberry" } },
            { "ClimbingChalk", new string[] { "攀岩粉", "Climbing Chalk" } },
            { "Cure-Some", new string[] { "疗伤药", "Cure-Some" } },
            { "Darkberry", new string[] { "暗莓", "Darkberry" } },
            { "Energy Elixir", new string[] { "能量灵药", "Energy Elixir" } },
            { "Lollipop_Evil", new string[] { "恶趣棒棒糖", "Follypop" } },
            { "Matchbook", new string[] { "火柴盒", "Matchbook" } },
            { "Painkillers", new string[] { "止痛药", "Medicine" } },
            { "Skyberry", new string[] { "粉荔莓", "Pink Kingberry" } },
            { "Wand of Wind", new string[] { "风之杖", "Wand of Wind" } },
            { "Warpsketball", new string[] { "太空篮球", "Warpsketball" } },
            { "Wonderberry", new string[] { "奇迹莓", "Wonderberry" } },
        };

        /// <summary>显式隐藏的物品 prefab 名（装饰/测试物品等）。</summary>
        public static readonly HashSet<string> HiddenExact = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase)
        {
            "BaseConstructable Variant",
            "BaseObject",
            "Berrynana UNUSED",
            "BingBong_Prop Variant",
            "Binoculars_Prop",
            "Bugle_Prop Variant",
            "Clusterberry_UNUSED",
            "Lollipop_Prop",
            "Mandrake_Hidden",
            "Portable Speaker",
            "Propeller",
            "Skull",
            "TestConstructable Variant",
            "foodTest",
        };

        /// <summary>需要隐藏的前缀（棋子等装饰物）。</summary>
        public static readonly string[] HiddenPrefixes = new string[]
        {
            "C_Bishop",
            "C_King",
            "C_Knight",
            "C_Pawn",
            "C_Queen",
            "C_Rook",
            "GuidebookPage",
        };

        /// <summary>需要隐藏的子串。</summary>
        public static readonly string[] HiddenSubstrings = new string[]
        {
            "_Prop",
            "_TEMP",
            "_UNUSED",
            "_Hidden",
        };

    }
}
